name: Vercel Deploy Hook

on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Webhook Trigger
        run: curl ${{ secrets.WEBHOOK_URL }}
