name: CI

on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Webhook Trigger
        uses: zzzze/webhook-trigger@v1.0.0
        with:
          data: "{\"event_type\":\"build\"}"
          webhook_url: ${{ secrets.WEBHOOK_URL }}
